# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            lbrs.io
tagline:          'The quieter you become, the more you are able to hear'
description:      'The <a href="">quieter you become</a>, the more you are able to hear'
url:              https://blog.lbrs.io/
#baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

linkedin: leubincloud
twitter: leubfish

author:
  name:           'LBRS Cdrc'
  url:            https://fr.gravatar.com/userimage/191316321/b1ece9b7c5cd093a314f491dbb7b49f0.png?size=200
  logo:           https://fr.gravatar.com/userimage/191316321/b1ece9b7c5cd093a314f491dbb7b49f0.png?size=200
paginate:         2
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:           https://github.com/cdrclbrs
